<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // One row per side. Two phones detect each other seconds apart and from
        // slightly different places, so each keeps its own time and coordinates
        // rather than sharing a single record.
        Schema::create('meetings', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('met_user_id')->constrained('users')->cascadeOnDelete();

            // The detecting phone's position, not a midpoint between the two.
            $table->decimal('latitude', 10, 7);
            $table->decimal('longitude', 10, 7);

            $table->timestamp('detected_at');

            // Set when the other side reports the mirror detection. Internal signal
            // only: it never reaches the client and never hides a meeting.
            $table->boolean('confirmed')->default(false);

            // Generated by the app. Lets a retry after a lost response return the
            // original outcome instead of creating a second meeting.
            $table->string('event_id', 64);

            $table->timestamps();

            $table->unique(['user_id', 'event_id']);

            // Cooldown lookup: has this pair already met around this time?
            $table->index(['user_id', 'met_user_id', 'detected_at']);

            // History listing, newest first.
            $table->index(['user_id', 'detected_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('meetings');
    }
};
