<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // What each phone actually sent. A meeting is shared, a report is not: both
        // riders may report the same encounter, seconds apart and from slightly
        // different places, and each keeps its own reading.
        //
        // It also carries idempotency. event_id is generated per phone, so the same
        // encounter has two different ones and a single column on meetings would have
        // nowhere to put the second.
        Schema::create('meeting_reports', function (Blueprint $table) {
            $table->id();
            $table->foreignId('meeting_id')->constrained()->cascadeOnDelete();
            $table->foreignId('reporter_id')->constrained('users')->cascadeOnDelete();

            // Generated by the app. Lets a retry after a lost response return the
            // original outcome instead of recording anything twice.
            $table->string('event_id', 64);

            $table->timestamp('detected_at');
            $table->decimal('latitude', 10, 7);
            $table->decimal('longitude', 10, 7);

            // Optional signal strength. Useless on its own, but collected from day one
            // because thresholds can only be tuned on data that was already gathered:
            // it is what will later separate "somebody within thirty metres" from
            // "stood next to each other at the lights".
            $table->smallInteger('rssi')->nullable();

            // Copied from the reporting device rather than joined at read time, so the
            // detection matrix behind the redesign — Android cannot see a backgrounded
            // iPhone — can be checked against real traffic with one grouped query.
            $table->string('platform')->nullable();

            $table->timestamps();

            $table->unique(['reporter_id', 'event_id']);
            $table->index(['meeting_id', 'reporter_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('meeting_reports');
    }
};
